import json
from typing import Dict, Any, Optional
from tools.registry import registry
from .notifier import send_notification

class Executor:
    def __init__(self):
        self.registry = registry

    def execute_plan(self, plan: Dict[str, Any]) -> str:
        """Parses the agent's plan JSON and executes each tool sequentially."""
        if not plan:
            return "No valid plan generated by the agent."
        
        steps = plan.get("plan")
        if not steps or not isinstance(steps, list):
            return "Plan JSON is missing 'plan' list or it is empty."

        total_steps = len(steps)
        final_output = []

        for i, action in enumerate(steps, 1):
            tool_name = action.get("tool")
            args = action.get("args", {})

            if not tool_name:
                final_output.append(f"Step {i}/{total_steps}: Error - missing 'tool' field.")
                continue

            # Check for dangerous tools
            if hasattr(self.registry, '_dangerous_tools') and tool_name in self.registry._dangerous_tools:
                print(f"\n⚠️  SAFETY ALERT: The agent wants to run a dangerous tool: {tool_name}({args})")
                send_notification("Agentic AI: Safety Alert", f"Action required for: {tool_name}")
                
                confirm = input("Confirm execution? (y/N): ").strip().lower()
                if confirm != 'y':
                    final_output.append(f"Step {i}/{total_steps}: Skipped - User denied permission for '{tool_name}'.")
                    continue

            tool_func = self.registry.get_tool(tool_name)
            if not tool_func:
                final_output.append(f"Step {i}/{total_steps}: Error - Tool '{tool_name}' not found.")
                continue

            try:
                print(f"-- Executing Step {i}/{total_steps}: {tool_name}({args})")
                result = tool_func(**args)
                final_output.append(f"Step {i}/{total_steps} ({tool_name}): {result}")
                
                # Graceful halt: If a tool explicitly returns an error string, abort the rest of the plan.
                if isinstance(result, str) and result.strip().startswith("Error"):
                    final_output.append(f"⚠️ Halt: Execution aborted at Step {i} due to tool error.")
                    break

            except Exception as e:
                final_output.append(f"Step {i}/{total_steps}: Error while calling '{tool_name}': {str(e)}")
                final_output.append(f"⚠️ Halt: Execution aborted at Step {i} due to exception.")
                break
        
        return "\n".join(final_output)

    def execute_action(self, action: Dict[str, Any]) -> str:
        """Legacy support for single actions, now wraps them into execute_plan logic."""
        if "plan" in action:
            return self.execute_plan(action)
        return self.execute_plan({"plan": [action]})
